site_name: eldpro
site_description: A CMV simulation application that also creates Electronic Logging Device logs for the simulated trips in accoradance to the HOS regulations
repo_url: https://github.com/kiraboibrahim/eld-pro
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/kiraboibrahim">kiraboibrahim</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
